import type { aElement } from './elements/a.d';
import type { abbrElement } from './elements/abbr.d';
import type { acronymElement } from './elements/acronym.d';
import type { addressElement } from './elements/address.d';
import type { appletElement } from './elements/applet.d';
import type { areaElement } from './elements/area.d';
import type { articleElement } from './elements/article.d';
import type { asideElement } from './elements/aside.d';
import type { audioElement } from './elements/audio.d';
import type { bElement } from './elements/b.d';
import type { baseElement } from './elements/base.d';
import type { bdiElement } from './elements/bdi.d';
import type { bdoElement } from './elements/bdo.d';
import type { bgsoundElement } from './elements/bgsound.d';
import type { bigElement } from './elements/big.d';
import type { blinkElement } from './elements/blink.d';
import type { blockquoteElement } from './elements/blockquote.d';
import type { bodyElement } from './elements/body.d';
import type { brElement } from './elements/br.d';
import type { buttonElement } from './elements/button.d';
import type { canvasElement } from './elements/canvas.d';
import type { captionElement } from './elements/caption.d';
import type { centerElement } from './elements/center.d';
import type { citeElement } from './elements/cite.d';
import type { codeElement } from './elements/code.d';
import type { colElement } from './elements/col.d';
import type { colgroupElement } from './elements/colgroup.d';
import type { contentElement } from './elements/content.d';
import type { dataElement } from './elements/data.d';
import type { datalistElement } from './elements/datalist.d';
import type { ddElement } from './elements/dd.d';
import type { delElement } from './elements/del.d';
import type { detailsElement } from './elements/details.d';
import type { dfnElement } from './elements/dfn.d';
import type { dialogElement } from './elements/dialog.d';
import type { dirElement } from './elements/dir.d';
import type { divElement } from './elements/div.d';
import type { dlElement } from './elements/dl.d';
import type { dtElement } from './elements/dt.d';
import type { emElement } from './elements/em.d';
import type { embedElement } from './elements/embed.d';
import type { fieldsetElement } from './elements/fieldset.d';
import type { figcaptionElement } from './elements/figcaption.d';
import type { figureElement } from './elements/figure.d';
import type { fontElement } from './elements/font.d';
import type { footerElement } from './elements/footer.d';
import type { formElement } from './elements/form.d';
import type { frameElement } from './elements/frame.d';
import type { framesetElement } from './elements/frameset.d';
import type { h1Element } from './elements/h1.d';
import type { h2Element } from './elements/h2.d';
import type { h3Element } from './elements/h3.d';
import type { h4Element } from './elements/h4.d';
import type { h5Element } from './elements/h5.d';
import type { h6Element } from './elements/h6.d';
import type { headElement } from './elements/head.d';
import type { headerElement } from './elements/header.d';
import type { hgroupElement } from './elements/hgroup.d';
import type { hrElement } from './elements/hr.d';
import type { htmlElement } from './elements/html.d';
import type { iElement } from './elements/i.d';
import type { iframeElement } from './elements/iframe.d';
import type { imageElement } from './elements/image.d';
import type { imgElement } from './elements/img.d';
import type { inputElement } from './elements/input.d';
import type { insElement } from './elements/ins.d';
import type { kbdElement } from './elements/kbd.d';
import type { keygenElement } from './elements/keygen.d';
import type { labelElement } from './elements/label.d';
import type { legendElement } from './elements/legend.d';
import type { liElement } from './elements/li.d';
import type { linkElement } from './elements/link.d';
import type { mainElement } from './elements/main.d';
import type { mapElement } from './elements/map.d';
import type { markElement } from './elements/mark.d';
import type { marqueeElement } from './elements/marquee.d';
import type { menuElement } from './elements/menu.d';
import type { menuitemElement } from './elements/menuitem.d';
import type { metaElement } from './elements/meta.d';
import type { meterElement } from './elements/meter.d';
import type { navElement } from './elements/nav.d';
import type { nobrElement } from './elements/nobr.d';
import type { noembedElement } from './elements/noembed.d';
import type { noframesElement } from './elements/noframes.d';
import type { noscriptElement } from './elements/noscript.d';
import type { objectElement } from './elements/object.d';
import type { olElement } from './elements/ol.d';
import type { optgroupElement } from './elements/optgroup.d';
import type { optionElement } from './elements/option.d';
import type { outputElement } from './elements/output.d';
import type { pElement } from './elements/p.d';
import type { paramElement } from './elements/param.d';
import type { pictureElement } from './elements/picture.d';
import type { plaintextElement } from './elements/plaintext.d';
import type { portalElement } from './elements/portal.d';
import type { preElement } from './elements/pre.d';
import type { progressElement } from './elements/progress.d';
import type { qElement } from './elements/q.d';
import type { rbElement } from './elements/rb.d';
import type { rpElement } from './elements/rp.d';
import type { rtElement } from './elements/rt.d';
import type { rtcElement } from './elements/rtc.d';
import type { rubyElement } from './elements/ruby.d';
import type { sElement } from './elements/s.d';
import type { sampElement } from './elements/samp.d';
import type { scriptElement } from './elements/script.d';
import type { sectionElement } from './elements/section.d';
import type { selectElement } from './elements/select.d';
import type { shadowElement } from './elements/shadow.d';
import type { slotElement } from './elements/slot.d';
import type { smallElement } from './elements/small.d';
import type { sourceElement } from './elements/source.d';
import type { spacerElement } from './elements/spacer.d';
import type { spanElement } from './elements/span.d';
import type { strikeElement } from './elements/strike.d';
import type { strongElement } from './elements/strong.d';
import type { styleElement } from './elements/style.d';
import type { subElement } from './elements/sub.d';
import type { summaryElement } from './elements/summary.d';
import type { supElement } from './elements/sup.d';
import type { tableElement } from './elements/table.d';
import type { tbodyElement } from './elements/tbody.d';
import type { tdElement } from './elements/td.d';
import type { templateElement } from './elements/template.d';
import type { textareaElement } from './elements/textarea.d';
import type { tfootElement } from './elements/tfoot.d';
import type { thElement } from './elements/th.d';
import type { theadElement } from './elements/thead.d';
import type { timeElement } from './elements/time.d';
import type { titleElement } from './elements/title.d';
import type { trElement } from './elements/tr.d';
import type { trackElement } from './elements/track.d';
import type { ttElement } from './elements/tt.d';
import type { uElement } from './elements/u.d';
import type { ulElement } from './elements/ul.d';
import type { varElement } from './elements/var.d';
import type { videoElement } from './elements/video.d';
import type { wbrElement } from './elements/wbr.d';
import type { xmpElement } from './elements/xmp.d';

declare namespace JSX {
  interface ElementClass {
    render: any;
  }

  interface IntrinsicElements {
    a: aElement;
    abbr: abbrElement;
    acronym: acronymElement;
    address: addressElement;
    applet: appletElement;
    area: areaElement;
    article: articleElement;
    aside: asideElement;
    audio: audioElement;
    b: bElement;
    base: baseElement;
    bdi: bdiElement;
    bdo: bdoElement;
    bgsound: bgsoundElement;
    big: bigElement;
    blink: blinkElement;
    blockquote: blockquoteElement;
    body: bodyElement;
    br: brElement;
    button: buttonElement;
    canvas: canvasElement;
    caption: captionElement;
    center: centerElement;
    cite: citeElement;
    code: codeElement;
    col: colElement;
    colgroup: colgroupElement;
    content: contentElement;
    data: dataElement;
    datalist: datalistElement;
    dd: ddElement;
    del: delElement;
    details: detailsElement;
    dfn: dfnElement;
    dialog: dialogElement;
    dir: dirElement;
    div: divElement;
    dl: dlElement;
    dt: dtElement;
    em: emElement;
    embed: embedElement;
    fieldset: fieldsetElement;
    figcaption: figcaptionElement;
    figure: figureElement;
    font: fontElement;
    footer: footerElement;
    form: formElement;
    frame: frameElement;
    frameset: framesetElement;
    h1: h1Element;
    h2: h2Element;
    h3: h3Element;
    h4: h4Element;
    h5: h5Element;
    h6: h6Element;
    head: headElement;
    header: headerElement;
    hgroup: hgroupElement;
    hr: hrElement;
    html: htmlElement;
    i: iElement;
    iframe: iframeElement;
    image: imageElement;
    img: imgElement;
    input: inputElement;
    ins: insElement;
    kbd: kbdElement;
    keygen: keygenElement;
    label: labelElement;
    legend: legendElement;
    li: liElement;
    link: linkElement;
    main: mainElement;
    map: mapElement;
    mark: markElement;
    marquee: marqueeElement;
    menu: menuElement;
    menuitem: menuitemElement;
    meta: metaElement;
    meter: meterElement;
    nav: navElement;
    nobr: nobrElement;
    noembed: noembedElement;
    noframes: noframesElement;
    noscript: noscriptElement;
    object: objectElement;
    ol: olElement;
    optgroup: optgroupElement;
    option: optionElement;
    output: outputElement;
    p: pElement;
    param: paramElement;
    picture: pictureElement;
    plaintext: plaintextElement;
    portal: portalElement;
    pre: preElement;
    progress: progressElement;
    q: qElement;
    rb: rbElement;
    rp: rpElement;
    rt: rtElement;
    rtc: rtcElement;
    ruby: rubyElement;
    s: sElement;
    samp: sampElement;
    script: scriptElement;
    section: sectionElement;
    select: selectElement;
    shadow: shadowElement;
    slot: slotElement;
    small: smallElement;
    source: sourceElement;
    spacer: spacerElement;
    span: spanElement;
    strike: strikeElement;
    strong: strongElement;
    style: styleElement;
    sub: subElement;
    summary: summaryElement;
    sup: supElement;
    table: tableElement;
    tbody: tbodyElement;
    td: tdElement;
    template: templateElement;
    textarea: textareaElement;
    tfoot: tfootElement;
    th: thElement;
    thead: theadElement;
    time: timeElement;
    title: titleElement;
    tr: trElement;
    track: trackElement;
    tt: ttElement;
    u: uElement;
    ul: ulElement;
    var: varElement;
    video: videoElement;
    wbr: wbrElement;
    xmp: xmpElement;
  }
}

export = JSX;
export as namespace JSX;
