import type { Element } from '../globals';

type inputAttributes = [
  'accept',
  'align',
  'alt',
  'capture',
  'checked',
  'dirname',
  'disabled',
  'form',
  'formAction',
  'formenctype',
  'formmethod',
  'formnovalidate',
  'formtarget',
  'list',
  'max',
  'maxLength',
  'min',
  'minlength',
  'multiple',
  'name',
  'pattern',
  'placeholder',
  'readOnly',
  'src',
  'step',
  'type_button',
  'type_checkbox',
  'type_color',
  'type_date',
  'type_datetime-local',
  'type_email',
  'type_file',
  'type_hidden',
  'type_image',
  'type_month',
  'type_number',
  'type_password',
  'type_radio',
  'type_range',
  'type_reset',
  'type_search',
  'type_submit',
  'type_tel',
  'type_text',
  'type_time',
  'type_url',
  'type_week',
  'useMap',
  'x-moz-errormessage'
];

export type inputElement = Element<inputAttributes>;
